/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import com.google.gson.JsonObject;

import org.hyperledger.fabric.gateway.Contract;

import javax.management.Notification;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("/test")
public class App {

    //Needed to run application locally
    static {
		System.setProperty("org.hyperledger.fabric.sdk.service_discovery.as_localhost", "true");
	}

    public String getGreeting() {
        return "Starting Java app";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        JsonObject json = new JsonObject();
        json.addProperty("PPSN", "3324784V");
        json.addProperty("pattern", "01234567");
        json.addProperty("passcode", "7q0z1em9");
        json.addProperty("cert", "undefined");

        JsonObject data = new JsonObject();
        data.addProperty("date", "11-02-2021");
        data.addProperty("product", "LEXAPRO");
        data.addProperty("productID", "G551");
        data.addProperty("productPackage", "");
        data.addProperty("quantity", "20");
        data.addProperty("doseStrength", "10MG");
        data.addProperty("doseType", "TABS");
        data.addProperty("doseQuantity", "1perday");
        data.addProperty("instruction", "TAKEONEDAILYASDIRECTED");
        data.addProperty("comment", "");

        JsonObject admin = new JsonObject();
        admin.addProperty("PPSN", "admin");

        RegisterUser.enrollAdmin();
        // RegisterUser.enrollUser(json);
        try {
            Authentication authentication = new Authentication();
            // json = authentication.authenticateUser(json);
            // if(json.get("cert").getAsString().equals("undefined")){
            //     System.out.println("Authentication failed please enter correct details");
            // } else {
                System.out.println("Authentication succeeded have a nice day");
                System.out.println(json.get("cert").getAsString());
                Contract contract = Connection.connect(admin);
                PrescriptionRequests.createPrescription(contract, data, json);
                PrescriptionRequests.getAllPrescriptions(contract);
            // }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @GET
    @Path("/getJSON")
    @Produces(MediaType.TEXT_PLAIN)
    public String getJSON(){
        return "cheese";
    }
}
